/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          default: 'var(--color-primary-default)',
          hover: 'var(--color-primary-hover)',
          active: 'var(--color-primary-active)',
        },
        secondary: {
          default: 'var(--color-secondary-default)',
        },
        accent: {
          default: 'var(--color-accent-default)',
        },
        neutral: {
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          900: 'var(--color-neutral-900)',
        },
        semantic: {
          success: 'var(--color-semantic-success)',
          warning: 'var(--color-semantic-warning)',
          error: 'var(--color-semantic-error)',
          info: 'var(--color-semantic-info)',
          'on-primary-text': 'var(--color-semantic-on-primary-text)',
          'on-success-text': 'var(--color-semantic-on-success-text)',
        },
      },
      spacing: {
        0: 'var(--spacing-0)',
        1: 'var(--spacing-1)',
        2: 'var(--spacing-2)',
        3: 'var(--spacing-3)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        7: 'var(--spacing-7)',
        8: 'var(--spacing-8)',
        9: 'var(--spacing-9)',
        10: 'var(--spacing-10)',
      },
      borderRadius: {
        0: 'var(--radius-0)',
        2: 'var(--radius-2)',
        4: 'var(--radius-4)',
        8: 'var(--radius-8)',
        16: 'var(--radius-16)',
        999: 'var(--radius-999)',
      },
      borderWidth: {
        none: 'var(--border-none)',
        sm: 'var(--border-sm)',
        md: 'var(--border-md)',
        lg: 'var(--border-lg)',
      },
      boxShadow: {
        none: 'var(--box-shadow-none)',
        sm: 'var(--box-shadow-sm)',
        md: 'var(--box-shadow-md)',
        lg: 'var(--box-shadow-lg)',
        xl: 'var(--box-shadow-xl)',
        focus: 'var(--box-shadow-focus)',
      },
      opacity: {
        transparent: 'var(--opacity-transparent)',
        light: 'var(--opacity-light)',
        subtle: 'var(--opacity-subtle)',
        medium: 'var(--opacity-medium)',
        strong: 'var(--opacity-strong)',
        heavy: 'var(--opacity-heavy)',
        solid: 'var(--opacity-solid)',
      },
      fontFamily: {
        inter: 'var(--font-family-inter)',
      },
      fontWeight: {
        thin: 'var(--font-weight-thin)',
        'extra-light': 'var(--font-weight-extra-light)',
        light: 'var(--font-weight-light)',
        regular: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        'semi-bold': 'var(--font-weight-semi-bold)',
        bold: 'var(--font-weight-bold)',
        'extra-bold': 'var(--font-weight-extra-bold)',
        black: 'var(--font-weight-black)',
      },
      lineHeight: {
        xs: 'var(--line-height-xs)',
        sm: 'var(--line-height-sm)',
        md: 'var(--line-height-md)',
        lg: 'var(--line-height-lg)',
        xl: 'var(--line-height-xl)',
        '2xl': 'var(--line-height-2xl)',
        '3xl': 'var(--line-height-3xl)',
        '4xl': 'var(--line-height-4xl)',
        '5xl': 'var(--line-height-5xl)',
      },
      fontSize: {
        'desktop-xxs': 'var(--font-size-desktop-xxs)',
        'desktop-xs': 'var(--font-size-desktop-xs)',
        'desktop-sm': 'var(--font-size-desktop-sm)',
        'desktop-md': 'var(--font-size-desktop-md)',
        'desktop-lg': 'var(--font-size-desktop-lg)',
        'desktop-xl': 'var(--font-size-desktop-xl)',
        'desktop-2xl': 'var(--font-size-desktop-2xl)',
        'desktop-3xl': 'var(--font-size-desktop-3xl)',
        'desktop-4xl': 'var(--font-size-desktop-4xl)',
        'desktop-5xl': 'var(--font-size-desktop-5xl)',
        'desktop-6xl': 'var(--font-size-desktop-6xl)',
        'desktop-7xl': 'var(--font-size-desktop-7xl)',
        'mobile-xxs': 'var(--font-size-mobile-xxs)',
        'mobile-xs': 'var(--font-size-mobile-xs)',
        'mobile-sm': 'var(--font-size-mobile-sm)',
        'mobile-md': 'var(--font-size-mobile-md)',
        'mobile-lg': 'var(--font-size-mobile-lg)',
        'mobile-xl': 'var(--font-size-mobile-xl)',
        'mobile-2xl': 'var(--font-size-mobile-2xl)',
        'mobile-3xl': 'var(--font-size-mobile-3xl)',
        'mobile-4xl': 'var(--font-size-mobile-4xl)',
      },
    },
  },
  plugins: [
    forms,
    typography,
  ],
}

